### ISSUE TITLE
It is not available on Windows

### ISSUE THREAD

**Issue by lzdyes** [tauri-apps/tauricon#23]
last night, I wanted to set an icon for my app, so i see: https://tauri.studio/docs/guides/icons

```
yarn global add github:tauri-apps/tauricon

[1/4] Resolving packages...
warning github:tauri-apps/tauricon > imagemin-optipng > exec-buffer > tempfile > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@tauri-apps/tauricon@0.0.0" with binaries:
      - tauricon
Done in 39.97s.
```
when i run it:

```
$ tauri

tauri Couldn't recognize the current folder as a part of a Tauri project. It must contain a `tauri.conf.json` file in any subfolder. +0ms
```

so, I clone the source code project.

run `yarn test`:
```
yarn run v1.22.18
$ yarn build
$ rimraf ./dist && rollup -c --silent
babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
$ cross-env NODE_OPTIONS=--experimental-vm-modules jest --runInBand --forceExit --no-cache --testPathIgnorePatterns="(build|dev)"
(node:14632) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  console.log
     tauri Couldn't recognize the current folder as a part of a Tauri project. It must contain a `tauri.conf.json` file in any subfolder. +0ms

      at warn (src/helpers/logger.ts:18:15)

  ●  process.exit called with "1"

      43 |       "Couldn't recognize the current folder as a part of a Tauri project. It must contain a `tauri.conf.json` file in any subfolder."
      44 |     )
    > 45 |     process.exit(1)
         |             ^
      46 |     return ''
      47 |   } else {
      48 |     return dirname(matches[0])

      at getTauriDir (src/helpers/app-paths.ts:45:13)
      at src/helpers/app-paths.ts:52:39
      at Object.<anonymous> (test/jest/__tests__/tauricon.spec.js:6:23)

 RUNS  test/jest/__tests__/tauricon.spec.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

i found this bug:
```
const getTauriDir = (): string => {
  const dir = process.env.__TAURI_TEST_APP_DIR ?? process.cwd()
  // eslint-disable-next-line
  const matches: string[] = glob.sync(join(dir, `**/tauri.conf.json`), {
    ignore: ['**/node_modules/**', '**/target/**']
  })

  if (matches.length === 0) {
    warn(
      "Couldn't recognize the current folder as a part of a Tauri project. It must contain a `tauri.conf.json` file in any subfolder."
    )
    process.exit(1)
    return ''
  } else {
    return dirname(matches[0])
  }
}
```

after modify code:
```
const getTauriDir = (): string => {
  const dir = process.env.__TAURI_TEST_APP_DIR ?? process.cwd()
  // eslint-disable-next-line
  const matches: string[] = glob.sync('**/tauri.conf.json', {
    cwd: dir,
    ignore: ['**/node_modules/**', '**/target/**']
  })

  if (matches.length === 0) {
    warn(
      "Couldn't recognize the current folder as a part of a Tauri project. It must contain a `tauri.conf.json` file in any subfolder."
    )
    process.exit(1)
    return ''
  } else {
    return resolve(dir, dirname(matches[0]))
  }
}
```

run test result:
```
yarn run v1.22.18
$ yarn build
$ rimraf ./dist && rollup -c --silent
babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
$ cross-env NODE_OPTIONS=--experimental-vm-modules jest --runInBand --forceExit --no-cache --testPathIgnorePatterns="(build|dev)"
(node:6376) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
  console.log
     app:spawn batch minify:. +0ms

      at log (src/helpers/logger.ts:18:15)

  console.error
    [Error: Input file is missing]

      530 |       writeFileSync(path.join(target, '/icon.ico'), out2)
      531 |     } catch (err) {
    > 532 |       console.error(err)
          |               ^
      533 |       throw err
      534 |     }
      535 |   }

      at Object.icns (src/tauricon.ts:532:15)
      at Object.make (src/tauricon.ts:235:5)
      at Object.<anonymous> (test/jest/__tests__/tauricon.spec.js:26:7)

  console.log
     app:spawn batch minify:. +3s

      at log (src/helpers/logger.ts:18:15)

 PASS  test/jest/__tests__/tauricon.spec.js (15.699 s)
  [CLI] tauri-icon internals
    √ tells you the version (616 ms)
  [CLI] tauri-icon builder
    √ will still use default compression if missing compression chosen (11928 ms)
    √ will not validate a non-file (19 ms)
    √ makes a set of icons with optipng (2626 ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        15.776 s
Ran all test suites.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
Done in 21.54s.
```

my tauri info:
```
$ tauri info

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 100.0.1185.36
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
  › Node.js: 14.18.3
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7
  › @tauri-apps/api [NPM]: 1.0.0-rc.3
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:8000/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .github
  ├─ .vscode
  ├─ dist
  ├─ docs
  ├─ node_modules
  ├─ scripts
  ├─ src
  └─ src-tauri
Done in 50.19s.
```

**Comment by lukasbach** [comment]
I have the same issue under Windows, running on the same folder in Windows WSL subsystem works, but directly on Windows I get this error.
